- name: Creating alertmanager user group
  group: name=alertmanager
  become: true

- name: Creating alertmanager user
  user:
    name: "alertmanager"
    group: "alertmanager"
    system: yes
    shell: "/sbin/nologin"
    comment: "alertmanager nologin User"
    createhome: "no"
    state: present

- name: Download alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version_alertmanager }}/alertmanager-{{ version_alertmanager }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy alertmanager executable to bin
  copy:
    src: "/tmp/alertmanager-{{ version_alertmanager }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "alertmanager"
    group: "alertmanager"
    remote_src: yes
    mode: 0755

- name: Delete alertmanager tmp folder
  file:
    path: '/tmp/alertmanager-{{ version_alertmanager }}.linux-amd64'
    state: absent

- name: Creates data directory
  file:
    path: "/data/alertmanager/"
    state: directory
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0755

- name: Creates config directory
  file:
    path: "/etc/alertmanager/"
    state: directory
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0755

- name: Copy config file
  copy:
    src: "{{ role_path }}/files/alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml

- name: Copy systemd init file
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Start alertmanager service
  service:
    name: alertmanager
    state: started
    enabled: yes

- name: Check if alertmanager is accessible
  uri:
    url: http://monitoring.svgsmsc.com:9093
    method: GET
    status_code: 200