before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null centos@app.svgsmsc.com "cd /var/www/wordpress/ && sudo chown -R centos /var/www/wordpress/ && exit"
    - rsync -arvzc -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./* centos@app.svgsmsc.com:/var/www/wordpress/
